apiVersion: v1
kind: Secret
metadata:
  name: {{ template "reactdo.fullname" . }}
  labels:
    app: {{ template "reactdo.name" . }}
    chart: {{ template "reactdo.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{ if .Values.reactdoPassword }}
  reactdo-password: {{ .Values.reactdoPassword | b64enc | quote }}
  {{ else }}
  reactdo-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
